language: cpp

dist: bionic
compiler:
- clang
os:
- linux

before_install:
  - wget https://apt.llvm.org/llvm.sh
  - chmod +x llvm.sh
  - sudo ./llvm.sh 9

addons:
  apt:
    update: true
    packages:
     - ninja-build
     - libglfw3-dev

script:
  - chmod +x autobuild && ./autobuild